#!/usr/bin/env python3
"""Buying Your FIRST Candle Kit? Watch This First — FORMAT v5.3 via buildkit."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from buildkit import th, br, build

# ===== ACT 1 hook =====
th("So you want to make your first candle, and you are about to buy a starter kit. Before you spend a penny, give me five minutes, because I can save you a lot of frustration.")
th("I have watched so many people buy a beginner candle kit, get one disappointing candle out of it, and quietly give up, thinking candle making just is not for them.")
th("And almost every time, it was not them. It was the kit. Most beginner kits are built to look complete in a photo, not to actually teach you how to make a good candle.")
br("A typical beginner candle kit box opened up with all its little pieces laid out.","opens a beginner candle kit box and lays out the little pieces of wax, wicks and jars on the bench")
th("So let me walk you through what is actually in these kits, what matters, what is filler, and how to spend your money so your very first candle actually works.")
# ===== ACT 2 why kits fail beginners =====
th("Here is the core problem with most starter kits. They give you a tiny bit of everything and not enough of anything to actually practice.")
th("You get enough wax for maybe two candles. So you get two attempts, total, to learn a craft that genuinely takes a few tries to click.")
br("A small bag of wax from a kit next to a single finished candle.","holds up a small bag of kit wax beside one finished candle to show how little it really makes")
th("And candle making is all about repetition. Your second candle is always better than your first. Your fifth is better than your second.")
th("A kit that only lets you fail once or twice almost guarantees you stop right before it would have started working. That is the real trap.")
th("The other big issue is mismatched parts. The wick in the kit often is not properly sized for the wax and the jar they gave you.")
th("So even if you follow the instructions perfectly, the candle can still tunnel or smoke, and you will blame yourself instead of the kit.")
# ===== ACT 3 what actually matters =====
th("So let me tell you what actually matters, the parts that decide whether your candle works, so you know where to focus.")
th("There are really only four things. The wax, the wick, the fragrance, and a thermometer. Everything else is just nice to have.")
br("The four essentials laid out in a row: wax, a wick, a fragrance bottle, and a thermometer.","lays out wax, a wick, an amber fragrance bottle and a thermometer in a neat row on the bench")
th("The wax is your foundation. For a beginner I always recommend a single, forgiving soy container wax, not a fancy blend you have to fight with.")
th("The wick has to be matched to that wax and your jar size. This is the part cheap kits get wrong the most, so it is worth getting right.")
th("The fragrance is where the joy is, but go easy. Beginners almost always overload the fragrance and it actually makes the candle worse, not better.")
th("And the thermometer. This is the one tool people skip, and it is the single most important thing for getting a candle that actually sets properly.")
# ===== ACT 4 the thermometer point =====
th("Let me dwell on that thermometer for a second, because it is the cheapest thing on the list and the one that matters the most.")
th("Wax has to be melted to a certain temperature, cooled to another to add fragrance, and cooled again to pour. Those are three different numbers.")
br("A thermometer being lowered into a pot of melted wax, the reading climbing.","lowers a thermometer into a pot of melted wax and watches the temperature reading slowly climb")
th("Without a thermometer you are guessing all three, and guessing the temperature is the number one reason beginner candles come out with sinkholes, wet spots and weak scent.")
th("A basic kitchen thermometer is a few dollars and it removes almost all of the guesswork in one go. If your kit does not include one, buy one separately. Do not skip it.")
th("Honestly, if I could only give a beginner one piece of advice, it would be this. Measure your temperatures. It fixes more problems than any expensive wax ever will.")
# ===== ACT 5 build your own vs buy a kit =====
th("So here is the question. Buy a kit, or just buy the parts separately? And my honest answer is, it depends on what you want.")
th("If you genuinely just want to try it once, as a fun afternoon, a kit is fine. Buy a kit, enjoy it, no pressure, no big investment.")
br("A small pile of separately bought supplies next to a boxed kit, being compared.","sets a small pile of separately bought candle supplies beside a boxed kit and compares the two")
th("But if you think you might actually love this, do not buy the tiny kit. Buy a slightly larger amount of one good wax, a few matched wicks, one fragrance you love, and a thermometer.")
th("It costs a little more up front, but it gives you six or eight candles worth of practice instead of two, and that is what makes it actually click.")
th("And every part you buy on purpose, sized and matched, instead of whatever the kit happened to include, means you actually learn what each part does.")
# ===== ACT 6 a simple first recipe =====
th("Let me give you a dead-simple first project, so you are not starting from a blank page.")
th("One pound of soy container wax. One eight ounce jar. One properly sized wick for that jar. And one ounce of fragrance oil, which is a gentle, safe load to start with.")
br("The simple first-candle setup arranged on the bench: wax, one jar, one wick, one fragrance bottle.","arranges a single jar, a wick, a bag of wax and one fragrance bottle together as a simple first setup")
th("Melt the wax, check your temperatures, add the fragrance in the right window, stir gently for two full minutes, and pour into a slightly warmed jar.")
th("Then, and this is the hard part for everyone, leave it completely alone to cool slowly. No fridge, no fan, no poking it. Just patience.")
th("That one recipe, done carefully, will teach you more than any twelve-piece kit, because every step is one you did on purpose and can repeat.")
# ===== ACT 7 mistakes to avoid =====
th("Before you go, let me save you from the three mistakes every single beginner makes, myself included, back in the day.")
th("One. Overloading the fragrance. More oil does not mean more scent. Past a certain point it just refuses to bind and ruins the burn. Stay in the safe range.")
br("An amber fragrance bottle being measured carefully on a small kitchen scale.","sets an amber fragrance bottle on a small kitchen scale and measures the fragrance carefully")
th("Two. Pouring too hot. Hot wax into a cold jar gives you wet spots and sinkholes. Let it cool into the proper window before it ever touches the glass.")
th("Three. Rushing the cooling. Shoving a candle in the fridge to set it faster wrecks the top every time. Slow and undisturbed always wins.")
th("Avoid those three, measure your temperatures, and your first real candle will be better than most people's tenth. I promise you that.")
# ===== ACT 7b understanding wax types =====
th("Let me spend a minute on wax, because this is the choice that overwhelms beginners the most, and it really does not need to.")
th("You will see soy, paraffin, coconut, beeswax, and a dozen blends, and every supplier swears theirs is the best. For your first candles, ignore almost all of it.")
br("Several different bags of wax lined up on the bench, one pulled forward.","lines up a few different bags of wax on the bench and pulls one forward, setting it apart from the rest")
th("Start with a single soy container wax. It is forgiving, it is widely available, it cleans up with soap and water, and it is made for exactly what you are doing.")
th("Soy is more patient with temperature mistakes than most waxes, which matters enormously when you are still learning to read your thermometer.")
th("Once you have made a dozen good soy candles, then by all means go explore coconut blends and the fancy stuff. But learn to walk on soy first.")
th("Picking one wax and staying with it for your first month teaches you more than hopping between five waxes ever could, because you learn how that one behaves.")
# ===== ACT 7c reading a fragrance label =====
th("Now fragrance, because this is where beginners spend the most and waste the most. Let me save you some money and some heartache.")
th("Every fragrance oil has a maximum load, usually printed on the bottle, often around ten percent. That is the most the wax can actually hold.")
br("An amber fragrance bottle being turned to show the load percentage on its label.","turns an amber fragrance bottle to face the camera, pointing at the load percentage on the label")
th("Beginners assume more oil means more scent, so they pour in extra, and the wax simply cannot absorb it. It pools, it ruins the burn, and it can even be unsafe.")
th("Start at around six to eight percent by weight, measured on a scale, not by eye. A little less fragrance that actually binds beats a lot that just sits there.")
th("And give your fragrance a curing period. A soy candle that has rested for a week or two will throw far more scent than one you burn the same day you pour it.")
th("So buy one fragrance you genuinely love, measure it properly, and let it cure. That single habit will make your candles smell better than most beginners ever manage.")
# ===== ACT 7d the tools that actually matter =====
th("Let me cut through the gadget aisle, because kits and shops will try to sell you a drawer full of tools you do not need yet.")
th("Here is the honest list. A pouring pot, a thermometer, a cheap kitchen scale, something to stir with, and wick holders to keep the wick centered. That is it.")
br("The five genuinely useful tools laid out together: a pouring pot, thermometer, scale, stirrer, and wick holder.","lays out a pouring pot, a thermometer, a small scale, a stirrer and a wick holder together in a neat group")
th("The scale matters more than people expect, because good candle making is done by weight, not by volume. You weigh your wax and you weigh your fragrance.")
th("Weighing is what makes a candle repeatable. A recipe in grams can be made the exact same way a hundred times. A recipe in cups never can.")
th("Everything beyond that little list, the fancy melters, the heat guns, the molds, can wait until you actually know you need them. Do not let gear become the hobby.")
th("I made beautiful candles for a year with a pot, a thermometer, a scale and a spoon. The tools did not make the candle. The temperatures did.")
# ===== ACT 7e your first afternoon =====
th("So let me paint you a picture of your very first candle afternoon, start to finish, so it feels completely doable, because it truly is.")
th("You clear a calm space, you weigh your wax, and you melt it gently while you watch the thermometer climb. No rushing, no high heat, just patience.")
br("A calm, tidy workspace ready for a first pour, everything laid out in order.","smooths a hand across a tidy workspace with wax, jar, wick and thermometer all laid out in order")
th("You let it cool to the fragrance window, you weigh in your oil, and you stir gently for two full minutes so it really binds into the wax.")
th("You let it cool a little more to the pour window, you set your wick straight, and you pour slowly and steadily into a slightly warmed jar.")
th("Then you walk away. You let it sit undisturbed, you let it cure for a week, and the first time you light it and it fills the room, you will be hooked for life.")
th("That is the whole craft, on your very first day. Not a kit with twelve mystery pieces. Just a few good ingredients, treated with care and a little patience.")
# ===== ACT 7f when it goes wrong =====
th("Now let me reassure you about something, because it matters more than any tip. Your first candle might not be perfect, and that is completely okay.")
th("You might get a sinkhole, or a slightly rough top, or a scent that is softer than you hoped. That does not mean you failed. That means you are learning to read your wax.")
br("A slightly imperfect first candle held gently in two hands, examined kindly.","cradles a slightly imperfect candle in both hands, turning it gently to look at the flawed top")
th("A sinkhole? Pour a little slower and cool a little slower next time. A rough top? A gentle warm pass over the surface smooths it right out.")
th("Weak scent? Let it cure longer before you judge it, and check the temperature you added the oil at. Almost every first-candle problem has a calm, simple fix.")
th("The makers you admire did not start perfect. They just kept going, candle after candle, learning one small thing each time. You are allowed to do the same.")
th("So make your first candle, enjoy its little flaws, write down what you would change, and pour another. That loop, repeated kindly, is the entire craft.")
# ===== ACT 8 CTA =====
th("So, before you buy that first kit, remember. The kit is not the craft. The craft is wax, a matched wick, gentle fragrance, a thermometer, and a little patience.")
th("Buy enough to actually practice, get one tool to stop the guessing, and give yourself permission to make a few imperfect candles on the way to a great one.")
th("If this saved you from a frustrating first kit, subscribe, because I walk through real candle making like this, one honest step at a time, every single week.")
th("And tell me in the comments what made you want to start making candles in the first place. I love reading those, and I will cheer you on.")

build(title="Buying Your FIRST Candle Kit? Watch This First", folder_name="video_firstkit_veo")
