#!/usr/bin/env python3
"""STOP Buying Wicks From Amazon (Do This Instead) — FORMAT v5.3 via buildkit."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from buildkit import th, br, build

# ===== ACT 0 MrBeast-style hook =====
th("Okay, in the next few minutes I am going to show you exactly why the wicks you are buying are quietly ruining your candles, the three things almost every cheap listing gets wrong, and precisely what to buy instead.")
th("And stick around to the very end, because I am going to give you the simple three-number formula that picks the perfect wick for any candle you ever make. That one trick alone is worth the whole video.")
# ===== ACT 1 hook =====
th("If you are buying your candle wicks off Amazon, I want you to stop, just for a minute, and let me explain what is actually going on.")
th("Because I did it for years. I bought the big assorted multi-packs, the ones with five hundred wicks for nine dollars, and I could not figure out why my candles kept failing.")
th("Tunneling, drowning, sooty black smoke, flames the size of a campfire. I blamed my wax, I blamed my fragrance, I blamed myself.")
th("It was none of those things. It was the wicks. And once I understood why, I never bought a candle wick off a random Amazon listing again.")
br("A messy pile of cheap assorted Amazon wicks tipped out onto the bench.","tips a bag of cheap assorted candle wicks out onto the bench and spreads them apart with her fingers")
th("So let me show you exactly what is wrong with most of these listings, and what I do instead now that costs about the same and works every single time.")
# ===== ACT 2 the core problem =====
th("Here is the thing nobody tells you. A wick is not one size fits all. The wick has to be matched to your specific wax, your jar diameter, and your fragrance load.")
th("That tiny detail is the whole game. The wick controls how much wax melts, how hot the candle burns, and whether it tunnels or drowns.")
th("Now think about those giant assorted packs. They give you a random grab bag of sizes with no real information about any of them.")
br("A cheap wick listing with vague labels held up next to a properly sized wick.","holds a tiny unlabeled cheap wick beside a clearly sized reference wick to show the difference")
th("The labels are usually meaningless. They will say small, medium, large, or some made-up code that matches no industry standard at all.")
th("So you have no idea what melt pool that wick is rated for, what wax series it was tested in, or honestly whether it was tested at all.")
th("You are basically guessing, every single pour, with a part that determines whether the candle works. That is why it feels so random.")
# ===== ACT 3 quality & safety =====
th("And it gets worse, because it is not just sizing. It is the quality of the wick itself.")
th("A good wick has a consistent braid and a clean, even core, so it burns at a steady, predictable rate the whole way down.")
br("A close look at a poorly braided cheap wick beside a clean evenly braided one.","lays two wicks side by side and runs a fingertip along each, showing one ragged and one smooth")
th("The cheap assorted ones are often unevenly braided, with cores that are inconsistent from wick to wick, even inside the same bag.")
th("That inconsistency is exactly why one candle from a batch burns perfectly and the next one, same wax, same jar, tunnels or smokes.")
th("And some of the really cheap ones use cores or coatings you genuinely do not want to be burning in your home for hours at a time.")
th("When you are paying for a clean burn and a safe flame, the wick is the last place you want to be cutting corners to save a couple of dollars.")
# ===== ACT 4 the pretabbed trap =====
th("Let me talk about the pre-tabbed wicks too, the ones that come already attached to those little metal bases.")
th("They look convenient, and for testing they can be fine, but the tabs on the cheap ones are often flimsy or not centered properly.")
br("A pre-tabbed wick sitting crooked and off-center in the bottom of a jar.","drops a pre-tabbed wick into an empty jar and shows it sitting crooked and off to one side")
th("A wick that is even slightly off-center will melt one side of the candle faster than the other, and you get that lopsided burn every time.")
th("And the glue dots they come with are usually weak, so the wick drifts while you pour, and now your perfectly centered wick is hugging the glass.")
th("So even the convenient option, bought cheap and blind, sets you up for the exact problems you were trying to avoid.")
# ===== ACT 5 what to do instead =====
th("Okay, so here is what I actually do instead, and it genuinely costs about the same money.")
th("I buy my wicks from a real candle-making supplier, not a marketplace. A supplier whose entire business is candles, not everything under the sun.")
br("A neat, clearly labeled box of wicks from a proper candle supplier on the bench.","sets down a tidy labeled box of wicks and turns it so the clear sizing information faces up")
th("The difference is information. A proper supplier tells you the exact wick series, the wax it was tested in, and the jar diameter range it suits.")
th("That means I can actually choose a wick on purpose, instead of pulling a mystery one out of a bag and hoping.")
th("And here is the money part. A focused pack of the right wick is usually a few dollars, basically the same as the junk pack, and every wick in it works.")
th("So you are not even really saving money with the cheap pack, because half of those wicks will go straight in the bin after they ruin a candle.")
# ===== ACT 6 how to choose =====
th("Now let me make choosing simple, because this is where people freeze up. You only need three numbers.")
th("Number one, your wax type and series. Number two, the inside diameter of your jar. Number three, roughly how much fragrance oil you are running.")
br("A jar being measured across the inside with a small ruler.","lays a small ruler across the mouth of an empty jar to measure the inside diameter")
th("Take those three things to a real supplier's wick guide, and they will point you to a starter wick to test. That is the key word, test.")
th("You buy two or three candidate sizes, you burn them properly, and you watch the melt pool. The right wick gives you a full, even pool with no soot.")
th("If it tunnels and leaves wax on the sides, you size up. If the flame is huge and smoking, you size down. It is genuinely that logical.")
th("Once you find the wick that matches your setup, you write it down and you buy that one in bulk. Now your candles are repeatable.")
# ===== ACT 7 the test burn =====
th("Let me quickly walk you through a proper test burn, because this is the step that replaces all the guessing.")
th("Burn the candle for one hour for every inch of jar diameter. So a three-inch jar gets about a three-hour first burn.")
br("A test candle burning with a clean, full melt pool reaching the edge of the glass.","leans in toward a burning test candle and points at the full even melt pool reaching the glass")
th("You want that melt pool to reach the edge of the glass right at the end of that burn. Full, even, and liquid all the way across.")
th("If it gets there too fast and the flame is roaring, the wick is too big. If there is a ring of hard wax left on the sides, it is too small.")
th("Do that once, properly, and you will never have to guess about that wax and jar combination again. One afternoon saves you months of failures.")
# ===== ACT 7b wick types =====
th("Now let me clear up something that confuses almost everyone, because the marketplace listings throw a dozen wick types at you with no explanation.")
th("There are really three families you need to know. Flat braided cotton, cored cotton, and wooden wicks. Each one behaves completely differently.")
th("Flat braided cotton is your everyday workhorse. It curls slightly as it burns, which helps it self-trim, and it suits most soy container candles beautifully.")
br("Three different wick types laid out in a row: a flat cotton wick, a cored wick, and a wooden wick.","lays out a flat cotton wick, a cored wick and a flat wooden wick in a row and points to each one")
th("Cored cotton wicks have a stiff center, often paper or cotton, that keeps them standing straight in softer waxes. They burn a little hotter and stand tall.")
th("And wooden wicks are the ones that crackle like a tiny fireplace. People adore them, but they are far fussier and need to be sized differently from cotton.")
th("The mistake is treating these as interchangeable. A wooden wick is not just a fancy cotton wick. It needs its own size chart and its own test burns entirely.")
th("So when a cheap listing dumps a mix of types into one bag, it is not giving you choice. It is giving you chaos, because none of them are documented.")
# ===== ACT 7c the wax-wick relationship =====
th("Here is the deeper truth that ties this all together. The wick and the wax are a team. You never choose one without thinking about the other.")
th("A natural soy wax has a low melt point and needs a gentler wick. A harder paraffin or a coconut blend holds more heat and often needs a stronger one.")
br("Two different waxes in jars side by side, one soft and creamy, one harder and glossy.","sets two jars of different wax side by side and presses a fingertip into each to show soft versus firm")
th("Add fragrance oil into the mix and it changes again, because fragrance load actually affects how the wax melts and how hard the wick has to work.")
th("This is exactly why a wick that is perfect in one recipe tunnels in another. Nothing is wrong with the wick. It is simply matched to a different wax.")
th("So whenever you change your wax, or you change your fragrance load by very much, you have to re-test your wick. The pairing is the whole craft.")
th("Once that clicks, you stop thinking there is one magic wick out there, and you start thinking in pairs. This wax, with this wick, at this fragrance load.")
# ===== ACT 7d storing and trimming =====
th("Two quick habits now that will save more candles than almost anything else, and they cost you nothing at all.")
th("First, store your wicks properly. Keep them flat, dry, and away from heat, because a bent or damp wick will never burn straight no matter how good it is.")
br("A neat box of wicks stored flat and organized by size on a shelf.","slides a tidy box of wicks onto a shelf, the wicks laid flat and grouped by size")
th("Second, and this is the big one, trim every wick to about a quarter inch before every single burn. Every time, without exception.")
th("A long wick gives you that tall, smoky, dancing flame and a mushroom of carbon on the tip. A trimmed wick gives you a calm, clean, even flame.")
th("People spend hours choosing the perfect wick and then ruin it by never trimming it. The trim is half the performance, and it takes five seconds.")
th("So even the best wick in the world needs these two things. Stored flat, and trimmed before every burn. Get those right and you are most of the way there.")
# ===== ACT 7e building a wick library =====
th("Let me give you the system I actually use, because once you have it, you never guess about wicks again. I call it a wick library.")
th("When you find a wick that works for a wax and jar combination, you write it down in a little log. The wax, the jar size, the fragrance load, and the exact wick.")
br("A small logbook open with wick pairings written in neat columns.","opens a small logbook on the bench showing neat columns of wax, jar size and wick pairings")
th("Over a few months, that log becomes the most valuable thing you own. It is your personal map of exactly what works, paid for in test burns.")
th("Now when a customer wants a bigger jar, or you want to try a new fragrance, you are not starting from zero. You glance at your log and you are already close.")
th("And keep a small drawer with a labeled envelope of each wick you actually use. Not five hundred mystery wicks. Twenty wicks you understand completely.")
th("That is the difference between someone who buys wicks and someone who knows wicks. A small, documented, tested collection beats a giant bag of guesses every time.")
# ===== ACT 8 verdict + CTA =====
th("So here is the bottom line. The problem was never that you are bad at making candles. The problem is buying a critical part blind.")
th("Stop buying random assorted wicks off a marketplace listing. Buy a small, properly documented pack from a real candle supplier, and test it once.")
th("It costs about the same money, it takes one afternoon, and it turns candle making from a frustrating guessing game into something you can actually repeat.")
th("Your wax and your fragrance were probably fine the whole time. They just never had a wick that was matched to them.")
th("If this finally explained why your candles kept failing, subscribe, because I break down one real candle problem like this every single week.")
th("And tell me in the comments what wax you are running, and I will help you figure out where to even start with your wicks.")

build(title="STOP Buying Wicks From Amazon (Do This Instead)", folder_name="video_wicks_veo")
